sudo: false
language: python
sudo: false
matrix:
    include:
        - os: Linux
          python: 3.6
        - os: Linux
          python: 3.7

# Install packages
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugg
  - conda create -n noisepy -c conda-forge python=3.7.3 numpy=1.16.2 numba pandas pycwt mpi4py=3.0.1
  - conda activate noisepy
  - pip install obspy pyasdf
  - pip install codecov coverage
  
# Run test
script:
  - ls src
  - coverage run src/S0A_download_ASDF_MPI.py
  - coverage run src/S1_fft_cc_MPI.py
  - coverage run src/S2_stacking.py
  - codecov
