        fig,ax = plt.subplots(2,sharex=True)
        ax[0].matshow(data/data.max(),cmap='seismic',extent=[-maxlag,maxlag,data.shape[0],1],aspect='auto')
        new = noise_module.NCF_denoising(data,np.min([Mdate,data.shape[0]]),Ntau,NSV)
        ax[1].matshow(new/new.max(),cmap='seismic',extent=[-maxlag,maxlag,data.shape[0],1],aspect='auto')
        ax[0].set_title('Filterd Cross-Correlations')
        ax[1].set_title('Denoised Cross-Correlations')
        ax[0].xaxis.set_visible(False)
        ax[1].set_xticks(t)
        ax[1].xaxis.set_ticks_position('bottom')
        ax[1].set_xlabel('Time [s]')
        plt.show()